**A company started to invest in digital marketing as a new way of their product
promotions. For that they collected data and decided to carry out a study on it.**

In [2]:
#importing libraries
import pandas as pd
import numpy as np

In [3]:
#Loading the dataset
sa=pd.read_csv('/content/Sales_add.csv')

In [4]:
#Vewing the head of the data
sa.head()

,Month,Region,Manager,Sales_before_digital_add(in $),Sales_After_digital_add(in $)
0,Month-1,Region - A,Manager - A,132921,270390
1,Month-2,Region - A,Manager - C,149559,223334
2,Month-3,Region - B,Manager - A,146278,244243
3,Month-4,Region - B,Manager - B,152167,231808
4,Month-5,Region - C,Manager - B,159525,258402

In [5]:
sa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64
 4   Sales_After_digital_add(in $)   22 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes

**● The company wishes to clarify whether there is any increase in sales after
stepping into digital marketing.**

Let m1 be the average sales after stepping into digital marketing and m2 be the average sales before stepping into digital marketing.we need to clarify whether there is any increase in sales after stepping into digital marketing.
Therefore our hypothesis is

H0: m1 <= m2

vs

H1: m1>m2

since sample size of both the groups is less than 30 we can use independent two sample T-test for testing the hypothesis

In [6]:
#Importing the function for T test
from scipy.stats import ttest_ind

In [11]:
t_stat,p_value=ttest_ind(sa['Sales_After_digital_add(in $)'],sa['Sales_before_digital_add(in $)'],alternative="greater")

In [39]:
t_stat

12.995084451110875

In [9]:
p_value

1.3071840034523225e-16

In [13]:
if p_value < 0.05:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Reject the null hypothesis.

Hence we reject the null hypothesis at 5% level of significance. Therefore from the given sample observations we can conclude that there is a statistically significant increase in sales after stepping into digital marketing.

**● The company needs to check whether there is any dependency between
the features “Region” and “Manager”.**

Here we need to use the Chisquare test of Independence to test whether there is any dependency between the features “Region” and “Manager”. The hypothesis to be tested is

H0: Region and Sales are independent of each other

vs

H1: Region and Sales are dependent on each other

In [40]:
#Since the data is not in the required format i need to reshape the data using melt function
sa1=pd.melt(sa,id_vars=['Manager','Region'],value_vars=['Sales_before_digital_add(in $)','Sales_After_digital_add(in $)'],value_name='Sales')

In [41]:
sa1

        Manager      Region                        variable   Sales
0   Manager - A  Region - A  Sales_before_digital_add(in $)  132921
1   Manager - C  Region - A  Sales_before_digital_add(in $)  149559
2   Manager - A  Region - B  Sales_before_digital_add(in $)  146278
3   Manager - B  Region - B  Sales_before_digital_add(in $)  152167
4   Manager - B  Region - C  Sales_before_digital_add(in $)  159525
5   Manager - B  Region - A  Sales_before_digital_add(in $)  137163
6   Manager - C  Region - C  Sales_before_digital_add(in $)  130625
7   Manager - A  Region - A  Sales_before_digital_add(in $)  131140
8   Manager - C  Region - B  Sales_before_digital_add(in $)  171259
9   Manager - B  Region - C  Sales_before_digital_add(in $)  141956
10  Manager - C  Region - B  Sales_before_digital_add(in $)  159339
11  Manager - A  Region - A  Sales_before_digital_add(in $)  178939
12  Manager - A  Region - B  Sales_before_digital_add(in $)  145062
13  Manager - A  Region - A  Sales_before_digital_add(in $)  151514
14  Manager - A  Region - C  Sales_before_digital_add(in $)  147463
15  Manager - B  Region - A  Sales_before_digital_add(in $)  177195
16  Manager - C  Region - A  Sales_before_digital_add(in $)  140862
17  Manager - B  Region - C  Sales_before_digital_add(in $)  167996
18  Manager - A  Region - B  Sales_before_digital_add(in $)  132135
19  Manager - B  Region - A  Sales_before_digital_add(in $)  152493
20  Manager - A  Region - B  Sales_before_digital_add(in $)  147425
21  Manager - C  Region - A  Sales_before_digital_add(in $)  130263
22  Manager - A  Region - A   Sales_After_digital_add(in $)  270390
23  Manager - C  Region - A   Sales_After_digital_add(in $)  223334
24  Manager - A  Region - B   Sales_After_digital_add(in $)  244243
25  Manager - B  Region - B   Sales_After_digital_add(in $)  231808
26  Manager - B  Region - C   Sales_After_digital_add(in $)  258402
27  Manager - B  Region - A   Sales_After_digital_add(in $)  256948
28  Manager - C  Region - C   Sales_After_digital_add(in $)  222106
29  Manager - A  Region - A   Sales_After_digital_add(in $)  230637
30  Manager - C  Region - B   Sales_After_digital_add(in $)  226261
31  Manager - B  Region - C   Sales_After_digital_add(in $)  193735
32  Manager - C  Region - B   Sales_After_digital_add(in $)  203175
33  Manager - A  Region - A   Sales_After_digital_add(in $)  276279
34  Manager - A  Region - B   Sales_After_digital_add(in $)  205180
35  Manager - A  Region - A   Sales_After_digital_add(in $)  253131
36  Manager - A  Region - C   Sales_After_digital_add(in $)  229336
37  Manager - B  Region - A   Sales_After_digital_add(in $)  187305
38  Manager - C  Region - A   Sales_After_digital_add(in $)  234908
39  Manager - B  Region - C   Sales_After_digital_add(in $)  191517
40  Manager - A  Region - B   Sales_After_digital_add(in $)  227040
41  Manager - B  Region - A   Sales_After_digital_add(in $)  212579
42  Manager - A  Region - B   Sales_After_digital_add(in $)  263388
43  Manager - C  Region - A   Sales_After_digital_add(in $)  243020

In [42]:
#Now use the crosstab function to create a crosstab between Manager and Region taking sales as the frequency
ctab=pd.crosstab(sa1['Region'],sa1['Manager'],values=sa1['Sales'],aggfunc='sum')

In [43]:
ctab

Manager     Manager - A  Manager - B  Manager - C
Region
Region - A      1624951      1123683      1121946
Region - B      1510751       383975       760034
Region - C       376799      1113131       352731

In [44]:
#Importing the function for chisquare test of independence
from scipy.stats import chi2_contingency

In [45]:
chistat,pvalue,dof,expected=chi2_contingency(ctab)

In [46]:
chistat

1140286.3053337836

In [47]:
pvalue

0.0

In [48]:
dof

4

In [50]:
if pvalue < 0.05:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Reject the null hypothesis.

Therefore the variables manager and region are dependent statistically at 4 degrees of freedom and 5% level of significance